### ISSUE TITLE
Test

### ISSUE THREAD

**Issue by ddavison** [joelworsham/monokai-theme-chromedevtools#1]
I'm having a problem with your repository.

When I run the following command, i get the following error.

`docker run -d joelworsham/monokai`

<details>
  <summary>Cannot find joelworsham/monokai</summary>
Cannot find joelworsham/monokai;
some giant;
stacktrace;
here;
some giant;
stacktrace;
here;
some giant;
stacktrace;
here;
some giant;
stacktrace;
here;
some giant;
stacktrace;
here;
some giant;
stacktrace;
here;
some giant;
stacktrace;
here;
some giant;
stacktrace;
here;
some giant;
stacktrace;
here;
some giant;
stacktrace;
here;
some giant;
stacktrace;
here;
some giant;
stacktrace;
here;

**Comment by ddavison** [comment]
<kbd>Ctrl</kbd>+<kbd>C</kbd>

**Comment by joelworsham** [comment]
<details>
  <summary>Here's a secret for you:</summary>
line break

line break
line break
line break
line break
line break
</details>

**Comment by ddavison** [comment]
<details>
  <summary>Test</summary>  

> Blockquote?

```java
some java code
```
# heading

**Comment by ddavison** [comment]
fixed.

**Comment by joelworsham** [comment]
plz fix bug

**Comment by ddavison** [comment]
fixed (again)

**Comment by joelworsham** [comment]
tx

**Comment by joelworsham** [comment]
Thanks for closing

**Comment by ddavison** [comment]
thanks for reopening.

**Comment by joelworsham** [comment]
No problem! :*

**Comment by joelworsham** [comment]
![](http://www.quotesgreetings.org/wp-content/uploads/2015/12/happyvalentinesdaywishes.png)

**Comment by ddavison** [comment]
![valentines-day-sms-whatsapp_messagescollection-com-07_759](https://cloud.githubusercontent.com/assets/2972876/22946169/ae390c4e-f2c4-11e6-8981-cf286593dd4d.png)
